# Generated by Django 3.2.5 on 2021-07-29 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='viewpost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('img', models.ImageField(upload_to='uploads/')),
                ('desc', models.TextField()),
                ('age', models.IntegerField()),
                ('new', models.BooleanField(default=False)),
            ],
        ),
    ]
